const Palette = {
	HOT_PINK: '#CF30AA',
	DEEP_PURPLE: '#6336D0',
	MIDNIGHT_BLUE: '#0D0D32',
	CHARCOAL_BLUE: '#2C2C51',
	BERRY_RED: '#AC0D58',
	TEAL: '#3EADAD',
	LIGHT_BLUE: '#e6eef1',
	INKY_BLUE: '#000020',
};

const Color = {
	PRIMARY: {
		MAIN: Palette.HOT_PINK,
		CONTRAST_TEXT: Palette.LIGHT_BLUE,
	},
	SECONDARY: {
		MAIN: Palette.DEEP_PURPLE,
		CONTRAST_TEXT: Palette.LIGHT_BLUE,
	},
	BACKGROUND: {
		MAIN: Palette.MIDNIGHT_BLUE,
		DARK: Palette.INKY_BLUE,
		CONTRAST_TEXT: Palette.LIGHT_BLUE,
	},
	SURFACE: {
		MAIN: Palette.CHARCOAL_BLUE,
		CONTRAST_TEXT: Palette.LIGHT_BLUE,
	},
	DANGER: {
		MAIN: Palette.BERRY_RED,
		CONTRAST_TEXT: Palette.LIGHT_BLUE,
	},
	SUCCESS: {
		MAIN: Palette.TEAL,
		CONTRAST_TEXT: Palette.LIGHT_BLUE,
	},
};

export default Color;
