const Palette = {
	ELECTRIC_SKY: '#2179dd',
	STEEL_BLUE: '#1b467b',
	DEEP_NIGHT: '#151419',
	ONYX: '#100f13',
	CHARCOAL: '#1C1B21',
	SMOKY_CHARCOAL: '#26262E',
	PALE_AZURE: '#f0f8ff',
	CRIMSON: '#dc3545',
	BURGUNDY: '#5d1017',
	SPRING_GREEN: '#28a745',
	DARK_FOREST: '#10431c',
	GOLDEN_ORANGE: '#fd7e14',
	RICH_AMBER: '#6c3201',
	CYAN_BLUE: '#17a2b8',
	TEAL_BLUE: '#09414a',
} as const;

const ThemeColor = {
	PRIMARY: {
		MAIN: Palette.ELECTRIC_SKY,
		DARK: Palette.STEEL_BLUE,
		CONTRAST_TEXT: Palette.PALE_AZURE,
	},
	BACKGROUND: {
		MAIN: Palette.DEEP_NIGHT,
		DARK: Palette.ONYX,
		CONTRAST_TEXT: Palette.PALE_AZURE,
	},
	SURFACE: {
		MAIN: Palette.CHARCOAL,
		LIGHT: Palette.SMOKY_CHARCOAL,
		CONTRAST_TEXT: Palette.PALE_AZURE,
	},
	DANGER: {
		MAIN: Palette.CRIMSON,
		DARK: Palette.BURGUNDY,
		CONTRAST_TEXT: Palette.PALE_AZURE,
	},
	SUCCESS: {
		MAIN: Palette.SPRING_GREEN,
		DARK: Palette.DARK_FOREST,
		CONTRAST_TEXT: Palette.PALE_AZURE,
	},
	WARNING: {
		MAIN: Palette.GOLDEN_ORANGE,
		DARK: Palette.RICH_AMBER,
		CONTRAST_TEXT: Palette.PALE_AZURE,
	},
	INFORMATION: {
		MAIN: Palette.CYAN_BLUE,
		DARK: Palette.TEAL_BLUE,
		CONTRAST_TEXT: Palette.PALE_AZURE,
	},
} as const;

export {ThemeColor};
